name: docker nginx image build
on:
  # github action 手动触发
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '19.3.0'
      - run: echo Hello


