name: Deploy To Tencent ECS
on:
  push:
    branches: ["master"]

jobs:
  Deploy-ECS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
         version: 8

      - name: Install & Build
        run: pnpm install --registry=https://registry.npmjs.org --frozen-lockfile && pnpm run build

      - name: Copy Files
        uses: xiehuan123/xiehuan-ssh@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          local: "./dist/*"
          remote: /data/nginx/html
