name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build And Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags:
           |
            ${{ secrets.ACR_REGISTRY }}/${{ ACR_NAMESPACE }}/${{ ACR_REPOSITORY }}:latest
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
